import logging
from typing import AsyncGenerator, Optional
import edge_tts
from edge_tts.exceptions import EdgeTTSException

from app.core.config import settings
from app.core.security import PayloadTooLargeError

logger = logging.getLogger("vocalsync.tts")

MAX_TTS_TEXT_LENGTH = 1000


class TextToSpeechService:
    """
    Asynchronous Text-to-Speech (TTS) engine powered by Microsoft Edge Online TTS.
    Provides 100% free neural voices with zero-disk I/O byte streaming.
    """
    def __init__(self):
        self.voice = settings.TTS_VOICE
        self.rate = settings.TTS_RATE
        self.volume = settings.TTS_VOLUME

    async def stream_audio_from_text(
        self, 
        text: str
    ) -> AsyncGenerator[bytes, None]:
        """
        Synthesizes a text string into an asynchronous stream of MP3 audio bytes.
        
        Args:
            text (str): The text response generated by the LLM.
        Yields:
            bytes: Sequential binary audio chunks ready for WebSocket transmission.
        Raises:
            PayloadTooLargeError: If text exceeds safety thresholds.
            RuntimeError: If the TTS synthesis service fails.
        """
        cleaned_text = text.strip()
        if not cleaned_text:
            logger.debug("Empty text received for TTS; skipping synthesis.")
            return

        if len(cleaned_text) > MAX_TTS_TEXT_LENGTH:
            logger.warning(
                f"TTS text exceeded limit ({len(cleaned_text)} chars). Truncating for safety."
            )
            cleaned_text = cleaned_text[:MAX_TTS_TEXT_LENGTH]

        logger.debug(
            f"Starting TTS synthesis with voice '{self.voice}' ({len(cleaned_text)} chars)..."
        )

        try:
            communicate = edge_tts.Communicate(
                text=cleaned_text,
                voice=self.voice,
                rate=self.rate,
                volume=self.volume
            )

            async for event in communicate.stream():
                if event["type"] == "audio" and event["data"]:
                    yield event["data"]

            logger.debug("TTS audio stream generation completed successfully.")

        except EdgeTTSException as e:
            logger.error(f"Edge-TTS synthesis error: {e}")
            raise RuntimeError(f"Voice synthesis failed: {str(e)}") from e
        except Exception as e:
            logger.critical(f"Unexpected exception during TTS generation: {e}", exc_info=True)
            raise RuntimeError("Internal text-to-speech processing error.") from e

    async def synthesize_to_bytes(self, text: str) -> bytes:
        """
        Helper method that aggregates the entire audio stream into a single 
        in-memory bytes payload. Useful for buffering full sentences.

        Args:
            text (str): The text string to synthesize.
        Returns:
            bytes: Complete MP3 audio file representation in memory.
        """
        audio_buffer = bytearray()
        try:
            async for chunk in self.stream_audio_from_text(text):
                audio_buffer.extend(chunk)
            return bytes(audio_buffer)
        except Exception as e:
            logger.error(f"Failed to synthesize complete byte buffer: {e}")
            return b""


tts_service = TextToSpeechService()